[tool.pytest.ini_options]
# Pytest configuration for Neurologix Smart Search POV

# Test discovery
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

# Minimum version
minversion = "7.0"

# Add import mode
addopts = [
    "--strict-markers",
    "--strict-config", 
    "--verbose",
    "--tb=short",
    "--import-mode=importlib"
]

# Test markers
markers = [
    "unit: Unit tests (fast, isolated)",
    "integration: Integration tests (require services)",
    "e2e: End-to-end tests (require full system)",
    "slow: Slow tests (>5 seconds)",
    "smoke: Smoke tests (critical functionality)",
    "regression: Regression tests",
    "security: Security-related tests",
    "performance: Performance tests",
    "database: Tests requiring database",
    "aws: Tests requiring AWS services",
    "mock: Tests using mocks/stubs"
]

# Logging
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(name)s: %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

# Coverage (if pytest-cov is installed)
# addopts = ["--cov=backend", "--cov-report=html", "--cov-report=term-missing"]

# Test timeout (if pytest-timeout is installed)
timeout = 300  # 5 minutes max per test

# Parallel execution (if pytest-xdist is installed)
# addopts = ["-n", "auto"]

# Environment variables for testing
env = [
    "TESTING=true",
    "LOG_LEVEL=DEBUG",
    "DB_NAME=neurologix_test_db"
]

# Filter warnings
filterwarnings = [
    "error",
    "ignore::UserWarning",
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning"
]
